In [1]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing multiplication using arithmetic operator
mul_ans = a*b
print(mul_ans)

# Performing multiplication using numpy function
mul_ans = np.multiply(a, b)
print(mul_ans)


[  10  360  130 3000]
[  10  360  130 3000]


In [2]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing division using arithmetic operators
div_ans = a/b
print(div_ans)

# Performing division using numpy functions
div_ans = np.divide(a, b)
print(div_ans)


[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


In [3]:
# Performing mod on two matrices
mod_ans = np.mod(a, b)
print(mod_ans)

#Performing remainder on two matrices
rem_ans=np.remainder(a,b)
print(rem_ans)

# Performing power of two matrices
pow_ans = np.power(a, b)
print(pow_ans)


[ 1  2  3 10]
[ 1  2  3 10]
[                 25          1934917632        137858491849
 1152921504606846976]
