In [1]:
import numpy as np
x = np.array([1, 2, 3])
print(type(x))
print(x)
print(x.dtype)

<class 'numpy.ndarray'>
[1 2 3]
int64


 If any of the numbers were a float the type for all numbers would be a float:

In [2]:
x = np.array([1.0, 2, 3])
print(x.dtype)

float64


In [3]:
import numpy as np
x = np.array([1, 2, 3])
print(x.shape)
print(f"Number of dimensions: {len(x.shape)}")
print(f"Length of array: {x.shape[0]}")

(3,)
Number of dimensions: 1
Length of array: 3


Like a regular list, values within an array can be accessed using indexing, where the index starts at zero:

In [4]:
print(x[0])  # first value in the array
1
print(x[1])  # second value in the array
2

1
2


2

Also change the contents of an array by setting the values using their index, e.g.,

In [5]:
x[2] = 100
print(x)

[  1   2 100]


As with a list, multiple values can be returned, or assigned, using a slice (the :):

In [6]:
x = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(x[2:4])  # get values from indexes 2 and 3
print()
print(x[4::2])
print()  # get values from index 4 to the end in steps of 2
x[0:3] = [20, 19, 18]  # re-assign the first three values
print(x)

[20 30]

[ 40  60  80 100]

[ 20  19  18  30  40  50  60  70  80  90 100]


In [7]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(arr_2d)

# Creating a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:")
print(arr_3d)


2D Array:
[[1 2 3]
 [4 5 6]]
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
x = np.zeros(10)  # an array of 10 zeros
print(x)

# Or, containing all ones (using the ones function):
x = np.ones(10)  # an array of 10 ones
print(x)


x = 2.3964 * np.ones(3)  # an array of 3 values of 2.3964
print(x)

# or equivalently
x = np.full(3, 2.3964)
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2.3964 2.3964 2.3964]
[2.3964 2.3964 2.3964]


In [9]:
# Create a 1D array filled with ones
ones_arr = np.ones(5)
print("1D Array filled with ones:")
print(ones_arr)

# Create a 2D array (2x3) filled with ones
ones_arr_2d = np.ones((2, 3))
print("2D Array (2x3) filled with ones:")
print(ones_arr_2d)


1D Array filled with ones:
[1. 1. 1. 1. 1.]
2D Array (2x3) filled with ones:
[[1. 1. 1.]
 [1. 1. 1.]]
